# Pandas for Data Analysis - Tutorial

Pandas is the essential library for data manipulation and analysis in Python. Think of it as Excel on steroids - a powerful library for working with structured data (tables, spreadsheets).

**Primary outcome:** You work with **Series** and **DataFrame** objects, align data, apply functions, and sort—matching the written lessons.

**Prerequisites:** [Introduction to Python](../1.2-intro-python/README.md) and [Data foundation with NumPy](../1.4-data-foundation-linear-algebra/README.md). See the [pandas README](./README.md).

> **Time needed:** About 90–150 minutes for a full pass.

## Learning Objectives
- Series and DataFrame fundamentals
- Data types and index
- Reindexing and dropping
- Arithmetic and data alignment
- Function application and mapping
- Sorting and ranking

## Setup

Install the required packages before running this notebook (run the cell below once).

In [32]:
# Install required packages (run once)
%pip install pandas numpy matplotlib

Requirement already satisfied: pandas in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (3.0.0)
Requirement already satisfied: numpy in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (2.4.2)
Requirement already satisfied: matplotlib in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /Users/wongshennan/Documents/work/skillsunion/dsai/tamkeen/docs/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

After installing, run the cells below to import pandas and continue the tutorial.

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
print(f"Pandas version: {pd.__version__}")

Pandas version: 3.0.0

## 1. Series: The Building Block

A Series is like a single column in a spreadsheet: a 1D array with labels (the index). Each value has a label, making it a "smart" array. DataFrames are built from Series (each column is a Series).

Use Series for: time series, categorical data, measurements, or any labeled 1D data.

In [57]:
# Create Series from list (auto index 0, 1, 2, ...)
grades = pd.Series([90, 85, 95, 78])
print("Series from list:")
print(grades)
print(f"\ndtype: {grades.dtype}, shape: {grades.shape}")

print(grades.index)
print(grades.array)

Series from list:
0    90
1    85
2    95
3    78
dtype: int64

dtype: int64, shape: (4,)
RangeIndex(start=0, stop=4, step=1)
<NumpyExtensionArray>
[90, 85, 95, 78]
Length: 4, dtype: int64

**Custom index, selection, and boolean masks**

**What this code does:**
- Builds `grades_labeled` from the same four scores as before, but passes `index=['Alice', 'Bob', 'Charlie', 'David']` so the row labels are names instead of 0..3.
- Prints the whole Series, then selects one value with `grades_labeled['Charlie']` (label-based lookup, not position).
- Computes `grades_labeled >= 90`, which returns a boolean Series aligned to the index, and passes it into `[ ]` to keep only rows where the value is True—so you see Alice and Charlie.

In [58]:
# Series with custom index (labels)
grades_labeled = pd.Series(
    [90, 85, 95, 78], 
    index=['Alice', 'Bob', 'Charlie', 'David']
    )

print("Series with custom labels:")
print(grades_labeled)

# Access by label
print(f"\nCharlie's grade: {grades_labeled['Charlie']}")

# Filter (boolean indexing)
print("\nPassing grades (>= 90):")
print(grades_labeled[grades_labeled >= 90])

Series with custom labels:
Alice      90
Bob        85
Charlie    95
David      78
dtype: int64

Charlie's grade: 95

Passing grades (>= 90):
Alice      90
Charlie    95
dtype: int64

**Series from a dictionary**

**What this code does:**
- Calls `pd.Series({...})` with student names as keys and grades as values; pandas turns keys into the index and values into the Series values.
- Prints the result—same labels as the previous cell, but the data came from a mapping instead of a list + index.

In [60]:
# [90, 85, 95, 78]
# index=['Alice', 'Bob', 'Charlie', 'David']
grades_labeled_dict = pd.Series(    
    {
        'Alice': 90,
        'Bob': 85,
        'Charlie': 95,
        'David': 78
    }
)

print("Series with custom labels:")
print(grades_labeled_dict)

Series with custom labels:
Alice      90
Bob        85
Charlie    95
David      78
dtype: int64

**Dictionary data with an explicit index order**

**What this code does:**
- Builds a population Series from a dict of city → millions, then passes `index=['New York', 'Tokyo', 'London', 'Paris']` to force row order and membership (same four cities, but ordered as listed).
- Prints the Series, then prints `population.mean()`—the arithmetic mean of the four displayed values.

In [ ]:
# Series from dictionary (keys become index)
population = pd.Series(
    {'New York': 8.4, 'London': 9.0, 'Tokyo': 37.4, 'Paris': 2.2},
    index=['New York', 'Tokyo', 'London', 'Paris']
)
print("Series from dict:")
print(population)
print(f"\nMean: {population.mean():.1f}")

Series from dict:
New York     8.4
Tokyo       37.4
London       9.0
Paris        2.2
dtype: float64

Mean: 14.2
8.4

## 2. DataFrame

A DataFrame is like an Excel spreadsheet: a 2D table with rows and columns.

Key components: **Columns** (named fields), **Index** (row labels), **Values** (the data). Create from dictionaries, lists of dicts, or NumPy arrays.

In [ ]:
path_to_csv = "path/to/csv/file.csv"
df = pd.read_csv(path_to_csv)

excel_file = "path/to/excel/file.xlsx"
df = pd.read_excel(excel_file)

parquet_file = "path/to/parquet/file.parquet"
df = pd.read_parquet(parquet_file)

**Build a DataFrame from column-wise lists**

**What this code does:**
- Builds `data` as a dict: each key becomes a column name, each value is a list of cell values; row `i` is built from the `i`-th entry of every list.
- Calls `pd.DataFrame(data)` and prints `"DataFrame:"`; the last expression `df` makes Jupyter render the HTML table.

In [80]:
# From dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['NYC', 'LA', 'Chicago', 'NYC'],
    'Salary': [70000, 85000, 90000, 75000]
}

# key - column name
# value - the different values in each column
# the combination of key/values of the same index position will form a row


df = pd.DataFrame(data)
print("DataFrame:")
df

DataFrame:

      Name  Age     City  Salary
0    Alice   25      NYC   70000
1      Bob   30       LA   85000
2  Charlie   35  Chicago   90000
3    Diana   28      NYC   75000

**Select columns by dtype**

**What this code does:**
- Runs `df.select_dtypes(exclude=['number'])` on the current `df`, which returns only columns whose dtype is not numeric (e.g. `Name`, `City` if they are object strings).

In [109]:
df.select_dtypes(exclude=['number'])

      Name     City
0    Alice      NYC
1      Bob       LA
2  Charlie  Chicago
3    Diana      NYC

**Shape, column names, and dtypes**

**What this code does:**
- Prints `df.shape` (rows, columns), `list(df.columns)`, and `df.dtypes` so you see dimensions, column names, and storage type per column.

In [81]:
# Basic info
print(f"Shape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print("Data Types:")
print(df.dtypes)

Shape: (4, 4)

Columns: ['Name', 'Age', 'City', 'Salary']
Data Types:
Name        str
Age       int64
City        str
Salary    int64
dtype: object

**`info()` and `describe()`**

**What this code does:**
- Calls `df.info()` to print row counts, column names, dtypes, and non-null counts.
- Calls `df.describe()` to summarize numeric columns (count, mean, std, min, quartiles, max) and returns it so Jupyter displays the summary table.

In [82]:
# DataFrame info and describe
print("Info:")
print(df.info())

print("\nStatistical Summary:")
df.describe()

Info:
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
 3   Salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes
None

Statistical Summary:

             Age        Salary
count   4.000000      4.000000
mean   29.500000  80000.000000
std     4.203173   9128.709292
min    25.000000  70000.000000
25%    27.250000  73750.000000
50%    29.000000  80000.000000
75%    31.250000  86250.000000
max    35.000000  90000.000000

**Column order and subset of columns**

**What this code does:**
- Rebuilds a DataFrame from the same `data` dict but passes `columns=["Name", "Salary", "Age", "City"]` to pick columns and set their left-to-right order (here `Salary` comes before `Age`).
- Displays `df2` as the last value in the cell.

In [106]:
# df.head(n=2)
# df.tail(n=2)


# data
df2 = pd.DataFrame(data, columns=["Name", "Salary", "Age", "City"])
# df2.City = "NYC"
df2

      Name  Salary  Age     City
0    Alice   70000   25      NYC
1      Bob   85000   30       LA
2  Charlie   90000   35  Chicago
3    Diana   75000   28      NYC

**The `Index` object**

**What this code does:**
- Creates `obj` as a short Series with labels `a`, `b`, `c`, then assigns `index = obj.index` and evaluates `index` so Jupyter shows the Index object’s contents.

In [114]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='str')

**Slicing an Index**

**What this code does:**
- Takes the Index from the previous cell and applies `index[1:]`, which returns a new Index containing the labels from position 1 onward (`b`, `c` for string labels).

In [115]:
index[1:]

Index(['b', 'c'], dtype='str')

**Constructing a `pd.Index`**

**What this code does:**
- Builds `labels = pd.Index(np.arange(1, 4))`, so the index holds integer labels `1`, `2`, `3`, and displays that `Index` object.

In [119]:
labels = pd.Index(np.arange(1,4))
labels

Index([1, 2, 3], dtype='int64')

**Align a Series to a prepared Index**

**What this code does:**
- Creates `obj2` with values `[1.5, -2.5, 0]` and uses the `labels` Index from the previous cell as its index—so the first value is paired with `1`, the second with `2`, etc.
- Displays `obj2`.

In [120]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

1    1.5
2   -2.5
3    0.0
dtype: float64

## 3. Data Types and Index

Each column has a dtype (int64, float64, object/string, bool, datetime64, categorical). The index labels rows and helps align data. Use `set_index()` / `reset_index()` to change the index. Use `astype()` or `pd.to_datetime()` for type conversion.

In [129]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                        index=['a', 'c', 'd'],
                        columns=['Ohio', 'Texas', 'California'])

frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

**Row `reindex` introduces missing rows**

**What this code does:**
- Starts from `frame` (3×3 with rows `a`, `c`, `d`).
- Calls `frame.reindex(['a', 'b', 'c', 'd'])` to force row order `a`–`d`; row `b` did not exist, so that row is filled with NaN.
- Prints `frame2.dtypes` to show dtypes after reindexing.

In [123]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2.dtypes

Ohio          float64
Texas         float64
California    float64
dtype: object

**Original `frame` reference**

**What this code does:**
- Evaluates `frame` again so you can compare the original 3×3 matrix to the reindexed variants in surrounding cells.

In [131]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

**Column `reindex`**

**What this code does:**
- Defines `states = ["Texas", "Utah", "California"]` and calls `frame.reindex(columns=states)` so columns are exactly those three names in that order; any column not present in `frame` (e.g. `Utah`) becomes all NaN.
- Displays `frame3`.

In [130]:
states = ["Texas", "Utah", "California"]
frame3 = frame.reindex(columns=states)
frame3

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

**`reindex` with `axis=`**

**What this code does:**
- Calls `frame.reindex(["a","b","c","d"], axis="index")` to reindex rows explicitly (same idea as `frame.reindex([...])` but axis is spelled out).
- Displays `frame4`.

In [133]:
frame4 = frame.reindex(["a","b","c","d"], axis="index")
frame4

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

**Mixed dtypes and memory**

**What this code does:**
- Builds `df_types` with int, string, float, and `pd.Categorical` columns.
- Prints `df_types.dtypes`, then `df_types.memory_usage(deep=True)` so you see bytes per column (with `deep=True` for object/category columns).

In [40]:
# Data types and index
df_types = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Height': [1.75, 1.80, 1.65],
    'Grade': pd.Categorical(['A', 'B', 'A'])
})
print("Data types:")
print(df_types.dtypes)
print("\nMemory usage:")
print(df_types.memory_usage(deep=True))

Data types:
ID           int64
Name           str
Height     float64
Grade     category
dtype: object

Memory usage:
Index     132
ID         24
Name      162
Height     24
Grade     103
dtype: int64

**Set and reset the index**

**What this code does:**
- Builds `sales_idx` with a month index and prints one element by label (`sales_idx['Feb']`).
- Builds `df_city`, then `set_index('City')` moves `City` into the row index; prints `reset_index()` to move it back to a column.

In [41]:
# Index: set and reset
sales_idx = pd.Series([100, 120, 140], index=['Jan', 'Feb', 'Mar'])
print("Series with custom index:", sales_idx['Feb'])

df_city = pd.DataFrame({'City': ['London', 'Paris'], 'Pop': [9, 2]})
df_city = df_city.set_index('City')
print("\nDataFrame with City as index:")
print(df_city)
print("\nReset index:")
print(df_city.reset_index())

Series with custom index: 120

DataFrame with City as index:
        Pop
City
London    9
Paris     2

Reset index:
     City  Pop
0  London    9
1   Paris    2

## 4. Reindexing and Dropping

`reindex()` reorganizes data to match new labels; missing entries get NaN. Chain `.ffill()` or `.bfill()` to fill gaps. `drop()` removes rows or columns; use `axis=1` for columns. Assign the result or use `inplace=True`.

In [42]:
# Reindexing
grades_s = pd.Series([85, 92, 78], index=['Alice', 'Bob', 'Charlie'])
new_idx = ['Alice', 'Bob', 'Charlie', 'David']
print("After reindex (added David):")
print(grades_s.reindex(new_idx))

sales_df = pd.DataFrame({'Revenue': [1000, 1500]}, index=['Jan', 'Mar'])
print("\nFill missing months:")
print(sales_df.reindex(['Jan', 'Feb', 'Mar']).ffill())

After reindex (added David):
Alice      85.0
Bob        92.0
Charlie    78.0
David       NaN
dtype: float64

Fill missing months:
     Revenue
Jan   1000.0
Feb   1000.0
Mar   1500.0

**Drop columns and rows**

**What this code does:**
- Builds a small `df_drop` with columns `name`, `grade`, `extra`.
- Prints `df_drop.drop('extra', axis=1)` (drop column) and `df_drop.drop(0)` (drop row label `0`).

In [43]:
# Dropping
df_drop = pd.DataFrame({'name': ['Alice', 'Bob'], 'grade': [85, 92], 'extra': [1, 2]})
print("Drop column:")
print(df_drop.drop('extra', axis=1))
print("\nDrop row:")
print(df_drop.drop(0))

Drop column:
    name  grade
0  Alice     85
1    Bob     92

Drop row:
  name  grade  extra
1  Bob     92      2

**Series before `drop`**

**What this code does:**
- Creates `obj` = `0.`..`4.` with index labels `a`–`e` and displays it—this object is the starting point for the next `drop` calls.

In [134]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

**Drop one row label**

**What this code does:**
- Calls `obj.drop("c")`, which returns a new Series without label `c` (values `0`–`4` remain for the other labels).
- Displays `new_obj`.

In [135]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

**Drop multiple labels**

**What this code does:**
- Calls `obj.drop(["d", "c"])` to remove two index labels in one call; returns a Series with only `a`, `b`, `e`.
- Displays `new_obj2`.

In [ ]:
new_obj2 = obj.drop(["d", "c"])
new_obj2

a    0.0
b    1.0
e    4.0
dtype: float64

**4x4 DataFrame for `drop`**

**What this code does:**
- Builds `data` as a 4×4 integer grid with column names `one`…`four` and displays it.

In [139]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                        columns=["one", "two", "three", "four"])
data

   one  two  three  four
0    0    1      2     3
1    4    5      6     7
2    8    9     10    11
3   12   13     14    15

**Drop rows by index values**

**What this code does:**
- Calls `data.drop(index=np.arange(1,4))` to drop rows whose index labels are `1`, `2`, and `3`, leaving only row `0` (and the four columns).
- Displays `data1`.

In [144]:
data1 = data.drop(index=np.arange(1,4)) # [1,3]
data1

   one  two  three  four
0    0    1      2     3

## 5. Arithmetic and Data Alignment

Pandas aligns data by index when doing arithmetic. Mismatched labels produce NaN. Use `fill_value` in `add()`, `sub()`, etc. to handle missing. `combine_first()` fills missing from a second DataFrame.

In [44]:
# Alignment by index
s1 = pd.Series({'Mon': 100, 'Tue': 120, 'Wed': 150})
s2 = pd.Series({'Tue': 110, 'Wed': 140, 'Thu': 130})
print("Difference (aligned by index):")
print(s1 - s2)

Difference (aligned by index):
Mon     NaN
Thu     NaN
Tue    10.0
Wed    10.0
dtype: float64

**`fill_value` and `combine_first`**

**What this code does:**
- Builds two overlapping DataFrames `df1` and `df2` on different index sets.
- Prints `df1.add(df2, fill_value=0)` so missing pairs in the aligned add are treated as 0 before addition.
- Builds `primary` and `secondary` with NaNs in `primary`, then prints `primary.combine_first(secondary)` to fill NaNs from `secondary` where `primary` is missing.

In [45]:
# fill_value and combine_first
df1 = pd.DataFrame({'A': [1, 2], 'B': [4, 5]}, index=['r1', 'r2'])
df2 = pd.DataFrame({'B': [7, 8], 'C': [10, 11]}, index=['r1', 'r3'])
print("Add with fill_value=0:")
print(df1.add(df2, fill_value=0))

primary = pd.DataFrame({'A': [1, np.nan, 3]}, index=['r1', 'r2', 'r3'])
secondary = pd.DataFrame({'A': [10, 20]}, index=['r1', 'r2'])
print("\nCombine (primary first):")
print(primary.combine_first(secondary))

Add with fill_value=0:
      A     B     C
r1  1.0  11.0  10.0
r2  2.0   5.0   NaN
r3  NaN   8.0  11.0

Combine (primary first):
       A
r1   1.0
r2  20.0
r3   3.0

## 6. Function Application and Mapping

`apply()` runs a function on each column (axis=0) or row (axis=1). For Series, use `map()` with a dict or function. Prefer vectorized ops (`df['A'] + df['B']`) over `apply()` when possible.

In [46]:
# apply() on column
grades_df = pd.DataFrame({'Math': [85, 76, 92], 'Science': [92, 88, 95]})
def to_letter(score):
    return 'A' if score >= 90 else 'B' if score >= 80 else 'C'
grades_df['Math_Grade'] = grades_df['Math'].apply(to_letter)
print(grades_df)

   Math  Science Math_Grade
0    85       92          B
1    76       88          C
2    92       95          A

**`map` on a Series**

**What this code does:**
- Creates `codes` with product codes and a `names` dict mapping each code to a product name.
- Prints `codes.map(names).tolist()`—each element is replaced by the dict value, producing `['Laptop', 'Mouse', 'Keyboard']`.

In [47]:
# map() on Series
codes = pd.Series(['A123', 'B456', 'C789'])
names = {'A123': 'Laptop', 'B456': 'Mouse', 'C789': 'Keyboard'}
print("Mapped:", codes.map(names).tolist())

Mapped: ['Laptop', 'Mouse', 'Keyboard']

## 7. Sorting and Ranking

`sort_values()` orders by column; `sort_index()` by index. `rank()` assigns positions; use `method='min'`, `'first'`, `'dense'` for ties. `nlargest()`/`nsmallest()` for efficient top-N.

In [48]:
# Create sales data for sorting examples
np.random.seed(42)
sales = pd.DataFrame({
    'Region': np.random.choice(['North', 'South', 'East'], 12),
    'Product': np.random.choice(['A', 'B', 'C'], 12),
    'Sales': np.random.randint(100, 500, 12)
})
sales.head()

  Region Product  Sales
0   East       A    352
1  North       C    335
2   East       B    444
3   East       A    148
4  North       B    158

**Sort by one or more columns**

**What this code does:**
- Prints the top 5 rows by `Sales` descending via `sort_values('Sales', ascending=False).head()`.
- Prints a multi-key sort: `sort_values(['Region', 'Sales'], ascending=[True, False])` so regions are alphabetical and within each region sales are highest-first.

In [49]:
# Sort by values
print("Top 5 by Sales:")
print(sales.sort_values('Sales', ascending=False).head())

print("\nSort by Region, then Sales:")
print(sales.sort_values(['Region', 'Sales'], ascending=[True, False]).head())

Top 5 by Sales:
   Region Product  Sales
11   East       B    463
2    East       B    444
7   South       B    370
0    East       A    352
1   North       C    335

Sort by Region, then Sales:
   Region Product  Sales
11   East       B    463
2    East       B    444
0    East       A    352
8    East       A    289
6    East       B    287

**Ranking and `nlargest`**

**What this code does:**
- On `scores`, prints `rank()` and `rank(method='min')` so you see how tie-breaking changes the rank numbers.
- Prints `sales.nlargest(3, 'Sales')`—the three rows with the largest `Sales` without sorting the full table.

In [50]:
# Ranking
scores = pd.Series([85, 92, 85, 95])
print("Rank (default):", scores.rank().tolist())
print("Rank (min):", scores.rank(method='min').tolist())
print("\nTop 3 with nlargest:")
print(sales.nlargest(3, 'Sales'))

Rank (default): [1.5, 3.0, 1.5, 4.0]
Rank (min): [1.0, 3.0, 1.0, 4.0]

Top 3 with nlargest:
   Region Product  Sales
11   East       B    463
2    East       B    444
7   South       B    370

## 8. Practice Exercises

### Exercise 1: Sort sales by Region then by Sales descending
### Exercise 2: Add a rank column for Sales (highest = 1)
### Exercise 3: Reindex a Series to add a missing month with forward fill

**Exercise 1**

**What you should write:**
- Call `sales.sort_values(['Region', 'Sales'], ascending=[True, False])` so rows are sorted first by `Region` ascending, then by `Sales` descending within each region (matches the printed exercise title above).
- Display or assign the result to confirm row order.

In [ ]:
# Your code here

**Exercise 2**

**What you should write:**
- Add a new column (e.g. `sales['Rank']`) equal to `sales['Sales'].rank(ascending=False)` so the largest sale gets rank 1 (adjust `ascending` if your prompt asks otherwise).

In [ ]:
# Your code here

**Exercise 3**

**What you should write:**
- Build a `Series` with a gap in the index (e.g. only `Jan` and `Mar`), then `reindex` to include `Feb` and use `.ffill()` so the missing month fills from the previous value.

In [ ]:
# Your code here

---

<details>
<summary>Click to see solutions</summary>

```python
# Exercise 1
sales.sort_values(['Region', 'Sales'], ascending=[True, False])

# Exercise 2
sales['Rank'] = sales['Sales'].rank(ascending=False)

# Exercise 3
s = pd.Series([100, 200], index=['Jan', 'Mar'])
s.reindex(['Jan', 'Feb', 'Mar']).ffill()
```
</details>

## Summary

You've learned:
- Series and DataFrame creation
- Data types and index
- Reindexing and dropping
- Arithmetic and data alignment
- Function application and mapping
- Sorting and ranking

## Next steps in this course

- Move on to [SQL fundamentals](../../2-data-wrangling/2.1-sql/README.md) in Module 2, or open the [course index](../../README.md).